### PR TITLE
Document use of NFS Advanced Edit feature. #262

### LINKED ISSUE #262: Document use of NFS Advanced Edit function
Thanks to forum user **dvgeek** for bringing to light our lack of documentation for the NFS Advanced Edit function.
While this feature is referenced several times in our forum, we should clearly (and briefly) document its use. A proper place would be at the end of the **NFS** section.
The forum post in question can be found below:
https://forum.rockstor.com/t/built-on-opensuse-testing-channel-live-early-adopters-developers-only/6592/50

### PR DESCRIPTION
**Pull request by FroggyFlox**
Fixes #262 
@phillxnet, ready for review, but note again that I have not had the opportunity to test rendering under an Apache2 server.

### This pull request's proposal
Adds a section on the NFS Advanced Edit feature, detailing its organization, its use, and what it does.
Adds two new screenshots supporting this new section.

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [x] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Review by phillxnet — CHANGES_REQUESTED** [review]
@FroggyFlox This is a nice addition. Thanks.
I've made a couple of suggestions, that I think help with flow. Though they may appear out of order in the commets!
See what you think?

**Comment by FroggyFlox** [comment]
Thanks a lot for improvements!

**Review by phillxnet — APPROVED** [review]

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for yet more improvements in this area. I'll merge and publish.

**Comment by phillxnet** [comment]
PR product published.

**Pull request merged**
