### PR TITLE
Update Documentation Copyright/Year (431)

### LINKED ISSUE #431: Update Documentation Copyright/Year
Suggestion to update the Copyright year in the `layout.html` as it currently shows 2015 as the year.

https://github.com/rockstor/rockstor-doc/blob/2c0bf98a95965fa93f09f3fbf660702fa1c96ef3/themes/rockstor/layout.html#L138-L142

either manually, or consider whether this can be done via Sphinx more dynamically (e.g. as described in #422 ) using the `|today|` substitution, but not sure whether that applies to html type files as well.

### PR DESCRIPTION
**Pull request by Hooverdan96**
Fixes #431.

### This pull request's proposal
Changes to be committed:
	modified:   themes/rockstor/layout.html
- adjust copyright message year to range including 2023.
- interim fix until a parametric solution can be implemented for the current year figure.

### Checklist
- [X] With the proposed changes no Sphinx errors or warnings are generated.
- [X] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Comment by Hooverdan96** [comment]
linkcheck failure, due to known broken link (addressed pull request #447)
(line   97) broken    https://btrfs.wiki.kernel.org/index.php/Glossary - 404 Client Error: Not Found for url: https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/index.php/Glossary.html

**Comment by phillxnet** [comment]
@Hooverdan96 Agreed we have some more refinements to get to in this area but this is a far better look than what we had. And we can approach other issues re this assignment as we go.

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for seeing to this. much appreciated as always.

**Comment by phillxnet** [comment]
PR product PRODUCTION published.

**Pull request merged**
