### PR TITLE
Add preferred btrfs support as btrfs IRC channel #382

### LINKED ISSUE #382: Add preferred upstream btrfs support as btrfs IRC channel
Influenced by the following btrfs mailing list post by Forza, it is proposed that we add in, above our existing btrfs mailing list link in the recently updated [Data Loss-prevention and Recovery in Rockstor](https://rockstor.com/docs/data_loss.html), the referenced Libera IRC Web client URL to the "#btrfs" IRC channel. We might also add in this community orientated btrfs support option into our generic 'Support': https://rockstor.com/docs/support.html#support section.

Btrfs mailing list post reference: https://lore.kernel.org/linux-btrfs/98b7da2.8b0b192.1810759a875@tnonline.net/

Proposed [Libera Chat](https://libera.chat/) Web client link: https://web.libera.chat/#btrfs 

This suggestion is motivated by our own team not being btrfs experts but more implementing an easy-to-use Web-UI type appliance on-top of our donor OS via our "Built on openSUSE" (Leap 15.3 currently) endeavour. As such in some cases, given our appliance nature, folks may well approach us seeking expert btrfs specific advise/support that might best be addressed to the wider btrfs community. However our existing references of ask-us via our forum and then the btrfs mailing list (with the existing published proviso that this could hold up the entirety of btrfs's world development), could do with at least an interim step: the IRC channel.

### PR DESCRIPTION
**Pull request by phillxnet**
Add further emphasis on importance of not 'bothering' the btrfs mailing list unless the needs are extreme.
Including additional 'note' formatting to highlight the extreme use only nature of this list.

Fixes #382

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [x] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Comment by phillxnet** [comment]
@FroggyFlox I've inadvertently added a 'breaking' link in this pr:
```
(       data_loss: line  182) broken    https://web.libera.chat/#btrfs - Anchor 'btrfs' not found
```
however it work just dandy in real-life.

Any ideas how we get around this. I'd really like to preserve the capability for folks to just click and go with the Web client pre-configured for the btrfs channel.

**Comment by FroggyFlox** [comment]
> Any ideas how we get around this. I'd really like to preserve the capability for folks to just click and go with the Web client pre-configured for the btrfs channel.

If I remember correctly, the link checker does support some sort of ignore list... I can't lookup at the moment but that could be an option.

**Comment by phillxnet** [comment]
We have the following doc entry regarding ignoring problematic links via a pattern:

https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder

**Comment by FroggyFlox** [comment]
Nice!
That's exactly what I was remembering.

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for the prompt there. The following:
```
linkcheck_ignore = [r'https://web.libera.chat/#btrfs']
```
in conf.py looks to have learnt it (at least locally):
```
make linkcheck
...
(       data_loss: line  182) -ignored- https://web.libera.chat/#btrfs
...
build succeeded.
```
Purposefully specific as best we know of any similar additions that also break our link checker.
I'll go ahead and commit and if all is well on final build test, merge ready to publish.
Don't want to bother you big brain unnecessarily with these otherwise trivial changes ;).

**Comment by phillxnet** [comment]
We have an additional linkcheck failure that is unrelated and thought to be temporary:
```
(interface/overview: line  166) broken    https://www.duplicati.com - HTTPSConnectionPool(host='www.duplicati.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f096f9e0ca0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
Proceeding with merge and publish as we can approach this new failure if it persists.

**Pull request merged**
