### PR TITLE
MinIO Rock-on write-up for rockstor

### PR DESCRIPTION
**Pull request by MikeMcPherson**
This document describes the installation and configuration process
for the new MinIO Rock-on.

> To ease and accelerate the PR submission, please use the template below to provide all required information.
> Please see our "Contributing to Rockstor documentation" in our [Rockstor's documentation](http://rockstor.com/docs/contribute_documentation.html)

Fixes #

### Checklist
- [X] With the proposed changes no Sphinx errors or warnings are generated.
- [ ] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Review by FroggyFlox — APPROVED** [review]
Hi @MikeMcPherson ,

Thanks for preparing such a nice write-up, that makes it all very clear! I personally like your write-up, all links are informative and working, screenshots are helpful; I believe it's ready to be merged.

For reference, your PR built successfully in Sphinx:
```
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 63 source files that are out of date
updating environment: [new config] 63 added, 0 changed, 0 removed
reading sources... [  1%] afp/apple_filing_protocol
reading sources... [  3%] analytics
reading sources... [  4%] benchmarks
reading sources... [  6%] clients
reading sources... [  7%] concepts
reading sources... [  9%] config_backup/config_backup
reading sources... [ 11%] contribute
reading sources... [ 12%] contribute_documentation
reading sources... [ 14%] contribute_rockons
reading sources... [ 15%] contribute_section
reading sources... [ 17%] dashboard
reading sources... [ 19%] data_loss
reading sources... [ 20%] disk-power-down/disk_power_down
reading sources... [ 22%] disks
reading sources... [ 23%] docker-based-rock-ons/discourse
reading sources... [ 25%] docker-based-rock-ons/jenkins
reading sources... [ 26%] docker-based-rock-ons/minio
reading sources... [ 28%] docker-based-rock-ons/openvpn-server
reading sources... [ 30%] docker-based-rock-ons/overview
reading sources... [ 31%] docker-based-rock-ons/owncloud
reading sources... [ 33%] docker-based-rock-ons/plex-media-server
reading sources... [ 34%] docker-based-rock-ons/syncthing
reading sources... [ 36%] docker-based-rock-ons/transmission-bittorrent
reading sources... [ 38%] docker-based-rock-ons/youtrack
reading sources... [ 39%] docker-based-rock-ons/zoneminder
reading sources... [ 41%] email_setup
reading sources... [ 42%] faq
reading sources... [ 44%] features
reading sources... [ 46%] gnome-disks-usb/gnome_disks_usb
reading sources... [ 47%] home_nas_guide
reading sources... [ 49%] howtos
reading sources... [ 50%] index
reading sources... [ 52%] install
reading sources... [ 53%] installer-howto/installer-howto
reading sources... [ 55%] intro
reading sources... [ 57%] kvm_setup
reading sources... [ 58%] luks/luks
reading sources... [ 60%] mdraid-mirror/boot_drive_howto
reading sources... [ 61%] multi_period_snapshots
reading sources... [ 63%] multiple_appliances
reading sources... [ 65%] network
reading sources... [ 66%] nfs_ops
reading sources... [ 68%] pools-btrfs
reading sources... [ 69%] pre-install-howto/pre-install-howto
reading sources... [ 71%] quickstart
reading sources... [ 73%] reinstall/reinstall
reading sources... [ 74%] reset-root-password
reading sources... [ 76%] rufus-howto/rufus_howto
reading sources... [ 77%] samba_ops
reading sources... [ 79%] services
reading sources... [ 80%] sftp/sftp
reading sources... [ 82%] share_replication
reading sources... [ 84%] shares-btrfs-subvolumes
reading sources... [ 85%] smart/smart
reading sources... [ 87%] snapshots-btrfs-snapshots
reading sources... [ 88%] soho
reading sources... [ 90%] support
reading sources... [ 92%] tasks
reading sources... [ 93%] uis
reading sources... [ 95%] update-channels/update_channels
reading sources... [ 96%] ups-setup/ups_setup
reading sources... [ 98%] users
reading sources... [100%] windows-shadow-copy

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  1%] afp/apple_filing_protocol
writing output... [  3%] analytics
writing output... [  4%] benchmarks
writing output... [  6%] clients
writing output... [  7%] concepts
writing output... [  9%] config_backup/config_backup
writing output... [ 11%] contribute
writing output... [ 12%] contribute_documentation
writing output... [ 14%] contribute_rockons
writing output... [ 15%] contribute_section
writing output... [ 17%] dashboard
writing output... [ 19%] data_loss
writing output... [ 20%] disk-power-down/disk_power_down
writing output... [ 22%] disks
writing output... [ 23%] docker-based-rock-ons/discourse
writing output... [ 25%] docker-based-rock-ons/jenkins
writing output... [ 26%] docker-based-rock-ons/minio
writing output... [ 28%] docker-based-rock-ons/openvpn-server
writing output... [ 30%] docker-based-rock-ons/overview
writing output... [ 31%] docker-based-rock-ons/owncloud
writing output... [ 33%] docker-based-rock-ons/plex-media-server
writing output... [ 34%] docker-based-rock-ons/syncthing
writing output... [ 36%] docker-based-rock-ons/transmission-bittorrent
writing output... [ 38%] docker-based-rock-ons/youtrack
writing output... [ 39%] docker-based-rock-ons/zoneminder
writing output... [ 41%] email_setup
writing output... [ 42%] faq
writing output... [ 44%] features
writing output... [ 46%] gnome-disks-usb/gnome_disks_usb
writing output... [ 47%] home_nas_guide
writing output... [ 49%] howtos
writing output... [ 50%] index
writing output... [ 52%] install
writing output... [ 53%] installer-howto/installer-howto
writing output... [ 55%] intro
writing output... [ 57%] kvm_setup
writing output... [ 58%] luks/luks
writing output... [ 60%] mdraid-mirror/boot_drive_howto
writing output... [ 61%] multi_period_snapshots
writing output... [ 63%] multiple_appliances
writing output... [ 65%] network
writing output... [ 66%] nfs_ops
writing output... [ 68%] pools-btrfs
writing output... [ 69%] pre-install-howto/pre-install-howto
writing output... [ 71%] quickstart
writing output... [ 73%] reinstall/reinstall
writing output... [ 74%] reset-root-password
writing output... [ 76%] rufus-howto/rufus_howto
writing output... [ 77%] samba_ops
writing output... [ 79%] services
writing output... [ 80%] sftp/sftp
writing output... [ 82%] share_replication
writing output... [ 84%] shares-btrfs-subvolumes
writing output... [ 85%] smart/smart
writing output... [ 87%] snapshots-btrfs-snapshots
writing output... [ 88%] soho
writing output... [ 90%] support
writing output... [ 92%] tasks
writing output... [ 93%] uis
writing output... [ 95%] update-channels/update_channels
writing output... [ 96%] ups-setup/ups_setup
writing output... [ 98%] users
writing output... [100%] windows-shadow-copy

generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [  0%] afp/time_machine_pool.png
copying images... [  0%] afp/tm_backups_single_user.png
copying images... [  0%] afp/tm_backups_share.png
copying images... [  1%] afp/add_afp_export_tm.png
copying images... [  1%] afp/tm_finder_connect_as.png
copying images... [  1%] afp/tm_connect_as_user_pass.png
copying images... [  2%] afp/finder_backups_on_rockstor.png
copying images... [  2%] afp/tm_select_backup_disk.png
copying images... [  2%] afp/tm_use_disk.png
copying images... [  3%] afp/tm_use_disk_password.png
copying images... [  3%] afp/tm_in_progress.png
copying images... [  3%] afp/tm_backup_complete.png
copying images... [  4%] smb_linux_network.png
copying images... [  4%] smb_linux_share.png
copying images... [  4%] smb_mac_auth.png
copying images... [  5%] smb_mac_share.png
copying images... [  5%] config_backup/conf_backup.png
copying images... [  5%] config_backup/conf_backup_taken.png
copying images... [  5%] config_backup/conf_uploaded.png
copying images... [  6%] dashboard-conf.gif
copying images... [  6%] cpu-widget.png
copying images... [  6%] memory-widget.png
copying images... [  7%] network-widget.png
copying images... [  7%] top-shares-widget.png
copying images... [  7%] disk-power-down/hdd_spin_down_config.jpg
copying images... [  8%] disk-power-down/hdd_only_one_spin_down_configured.png
copying images... [  8%] disk-power-down/hdds_active_idle.png
copying images... [  8%] disk-power-down/hdds_in_standby.png
copying images... [  9%] disk-power-down/plex_update_library.png
copying images... [  9%] images/disks_overview.png
copying images... [  9%] images/existing-btrfs-whole-disk-import-tooltip.png
copying images... [ 10%] images/existing-btrfs-whole-disk-config-tooltip.png
copying images... [ 10%] images/whole-disk-btrfs-import-done.png
copying images... [ 10%] images/existing-btrfs-partition-import-tooltip.png
copying images... [ 11%] images/config-drive-role-page.png
copying images... [ 11%] images/partitioned-disk-pre-redirect-role.png
copying images... [ 11%] images/select-btrfs-partition-redirect.png
copying images... [ 11%] images/post-role-existing-btrfs-partition-import-tooltip.png
copying images... [ 12%] images/active-btrfs-partition-redirect.png
copying images... [ 12%] images/imported-btrfs-in-partition.png
copying images... [ 12%] images/whole-disk-wipe.png
copying images... [ 13%] images/disk_detached.png
copying images... [ 13%] images/disk_delete_confirmation.png
copying images... [ 13%] docker-based-rock-ons/discourse_install.png
copying images... [ 14%] docker-based-rock-ons/discourse_share.png
copying images... [ 14%] docker-based-rock-ons/discourse_port.png
copying images... [ 14%] docker-based-rock-ons/discourse_email_config.png
copying images... [ 15%] docker-based-rock-ons/discourse_verify.png
copying images... [ 15%] docker-based-rock-ons/discourse_installing.png
copying images... [ 15%] docker-based-rock-ons/discourse_on.png
copying images... [ 16%] docker-based-rock-ons/discourse_ui.png
copying images... [ 16%] docker-based-rock-ons/jenkins_install.png
copying images... [ 16%] docker-based-rock-ons/jenkins_share.png
copying images... [ 16%] docker-based-rock-ons/jenkins_share_owner.png
copying images... [ 17%] docker-based-rock-ons/jenkins_ports.png
copying images... [ 17%] docker-based-rock-ons/jenkins_verify.png
copying images... [ 17%] docker-based-rock-ons/jenkins_installing.png
copying images... [ 18%] docker-based-rock-ons/jenkins_on.png
copying images... [ 18%] docker-based-rock-ons/jenkins_ui.png
copying images... [ 18%] docker-based-rock-ons/minio_install.png
copying images... [ 19%] docker-based-rock-ons/minio_share.png
copying images... [ 19%] docker-based-rock-ons/minio_port.png
copying images... [ 19%] docker-based-rock-ons/minio_environment.png
copying images... [ 20%] docker-based-rock-ons/minio_submit.png
copying images... [ 20%] docker-based-rock-ons/minio_installing.png
copying images... [ 20%] docker-based-rock-ons/minio_finished.png
copying images... [ 21%] docker-based-rock-ons/openvpn_install.png
copying images... [ 21%] docker-based-rock-ons/openvpn_port.png
copying images... [ 21%] docker-based-rock-ons/openvpn_address.png
copying images... [ 22%] docker-based-rock-ons/openvpn_verify.png
copying images... [ 22%] docker-based-rock-ons/openvpn_exitcode.png
copying images... [ 22%] docker-based-rock-ons/openvpn_certs.png
copying images... [ 22%] docker-based-rock-ons/openvpn_on.png
copying images... [ 23%] docker-based-rock-ons/rockons_root_share.png
copying images... [ 23%] docker-based-rock-ons/small_services.png
copying images... [ 23%] docker-based-rock-ons/rockons_root_config.png
copying images... [ 24%] docker-based-rock-ons/rockons_page.png
copying images... [ 24%] docker-based-rock-ons/addstorage_wrench.png
copying images... [ 24%] docker-based-rock-ons/addstorage_settings_summary.png
copying images... [ 25%] docker-based-rock-ons/addstorage_share_selection.png
copying images... [ 25%] docker-based-rock-ons/addstorage_settings_verification.png
copying images... [ 25%] docker-based-rock-ons/addlabels_settings_summary.png
copying images... [ 26%] docker-based-rock-ons/addlabels_container_selection.png
copying images... [ 26%] docker-based-rock-ons/addlabels_labels_selection.png
copying images... [ 26%] docker-based-rock-ons/owncloud_install.png
copying images... [ 27%] docker-based-rock-ons/owncloud_shares.png
copying images... [ 27%] docker-based-rock-ons/owncloud_port.png
copying images... [ 27%] docker-based-rock-ons/owncloud_db.png
copying images... [ 27%] docker-based-rock-ons/owncloud_verify.png
copying images... [ 28%] docker-based-rock-ons/owncloud_installing.png
copying images... [ 28%] docker-based-rock-ons/owncloud_on.png
copying images... [ 28%] docker-based-rock-ons/owncloud_info.png
copying images... [ 29%] docker-based-rock-ons/owncloud_ui.png
copying images... [ 29%] docker-based-rock-ons/plex_install.png
copying images... [ 29%] docker-based-rock-ons/plex_shares.png
copying images... [ 30%] docker-based-rock-ons/plex_share_owner.png
copying images... [ 30%] docker-based-rock-ons/plex_user_info.png
copying images... [ 30%] docker-based-rock-ons/plex_port.png
copying images... [ 31%] docker-based-rock-ons/plex_uid_gid_version.png
copying images... [ 31%] docker-based-rock-ons/plex_verify.png
copying images... [ 31%] docker-based-rock-ons/plex_installing.png
copying images... [ 32%] docker-based-rock-ons/plex_on.png
copying images... [ 32%] docker-based-rock-ons/plex_info.png
copying images... [ 32%] docker-based-rock-ons/plex_spanner.png
copying images... [ 33%] docker-based-rock-ons/plex_tos.png
copying images... [ 33%] docker-based-rock-ons/plex_server_setup.png
copying images... [ 33%] docker-based-rock-ons/plex_ss_add_library.png
copying images... [ 33%] docker-based-rock-ons/plex_ss_add_library_type.png
copying images... [ 34%] docker-based-rock-ons/plex_ss_add_library_movies.png
copying images... [ 34%] docker-based-rock-ons/plex_ss_add_library_folders.png
copying images... [ 34%] docker-based-rock-ons/plex_ss_add_library_data.png
copying images... [ 35%] docker-based-rock-ons/plex_ss_add_library_data_movies.png
copying images... [ 35%] docker-based-rock-ons/plex_ss_outside_stream.png
copying images... [ 35%] docker-based-rock-ons/plex_dashboard.png
copying images... [ 36%] docker-based-rock-ons/syncthing_install.png
copying images... [ 36%] docker-based-rock-ons/syncthing_shares.png
copying images... [ 36%] docker-based-rock-ons/syncthing_ports.png
copying images... [ 37%] docker-based-rock-ons/syncthing_verify.png
copying images... [ 37%] docker-based-rock-ons/syncthing_on.png
copying images... [ 37%] docker-based-rock-ons/syncthing_allow_anon.png
copying images... [ 38%] docker-based-rock-ons/syncthing_ui.png
copying images... [ 38%] docker-based-rock-ons/transmission_install.png
copying images... [ 38%] docker-based-rock-ons/transmission_share.png
copying images... [ 38%] docker-based-rock-ons/transmission_ports.png
copying images... [ 39%] docker-based-rock-ons/transmission_user.png
copying images... [ 39%] docker-based-rock-ons/transmission_verify.png
copying images... [ 39%] docker-based-rock-ons/transmission_on.png
copying images... [ 40%] docker-based-rock-ons/transmission_ui.png
copying images... [ 40%] docker-based-rock-ons/youtrack_groups_create.png
copying images... [ 40%] docker-based-rock-ons/youtrack_users_create.png
copying images... [ 41%] docker-based-rock-ons/youtrack_access_control.png
copying images... [ 41%] docker-based-rock-ons/youtrack_install.png
copying images... [ 41%] docker-based-rock-ons/youtrack_install_shares.png
copying images... [ 42%] docker-based-rock-ons/youtrack_install_summary.png
copying images... [ 42%] docker-based-rock-ons/youtrack_installed.png
copying images... [ 42%] docker-based-rock-ons/youtrack_token.png
copying images... [ 43%] docker-based-rock-ons/zoneminder_install.png
copying images... [ 43%] docker-based-rock-ons/zoneminder_shares.png
copying images... [ 43%] docker-based-rock-ons/zoneminder_port.png
copying images... [ 44%] docker-based-rock-ons/zoneminder_verify.png
copying images... [ 44%] docker-based-rock-ons/zoneminder_installing.png
copying images... [ 44%] docker-based-rock-ons/zoneminder_on.png
copying images... [ 44%] docker-based-rock-ons/zoneminder_ui_popups_blocked.png
copying images... [ 45%] docker-based-rock-ons/zoneminder_ui_popups_unblocking.png
copying images... [ 45%] docker-based-rock-ons/zoneminder_info.png
copying images... [ 45%] docker-based-rock-ons/zoneminder_options_images.png
copying images... [ 46%] docker-based-rock-ons/zoneminder_options_path_change.png
copying images... [ 46%] docker-based-rock-ons/zoneminder_path_change_restart_message.png
copying images... [ 46%] docker-based-rock-ons/zoneminder_ui_flat.png
copying images... [ 47%] email_init.png
copying images... [ 47%] email_config.png
copying images... [ 47%] email_done.png
copying images... [ 48%] email_test.png
copying images... [ 48%] gnome-disks-usb/right_click_image_writer.png
copying images... [ 48%] gnome-disks-usb/disks_restore_disk_image_dialog.png
copying images... [ 49%] gnome-disks-usb/disks_restore_image.png
copying images... [ 49%] gnome-disks-usb/disks_confirmation_dialog.png
copying images... [ 49%] gnome-disks-usb/disks_restore_in_progress.png
copying images... [ 50%] images/install-update.png
copying images... [ 50%] installer-howto/initial_screen.png
copying images... [ 50%] installer-howto/select_installation_disk.png
copying images... [ 50%] installer-howto/destroy-all-data.png
copying images... [ 51%] installer-howto/loading-rockstor.png
copying images... [ 51%] installer-howto/select_locale.png
copying images... [ 51%] installer-howto/select_keyboard.png
copying images... [ 52%] installer-howto/gplv2_license_agreement.png
copying images... [ 52%] installer-howto/select_time_zone.png
copying images... [ 52%] installer-howto/enter_root_password.png
copying images... [ 53%] installer-howto/confirm_root_password.png
copying images... [ 53%] installer-howto/wait_for_rockstor_tasks.png
copying images... [ 53%] installer-howto/root_login_myip.png
copying images... [ 54%] installer-howto/self_signed_certificate_advanced.png
copying images... [ 54%] installer-howto/self_signed_certificate_accept.png
copying images... [ 54%] installer-howto/initial_rockstor_setup_screen.png
copying images... [ 55%] installer-howto/eula-page.png
copying images... [ 55%] installer-howto/initial_welcome_banner.png
copying images... [ 55%] installer-howto/dashboard.png
copying images... [ 55%] installer-howto/update_channel_reminder_banner.png
copying images... [ 56%] vmm.png
copying images... [ 56%] vmm_add_volumes.png
copying images... [ 56%] vmm_system_drive.png
copying images... [ 57%] vmm_volumes_created.png
copying images... [ 57%] vmm_iso_step1.png
copying images... [ 57%] vmm_iso_os_step2.png
copying images... [ 58%] vmm_ram_step3.png
copying images... [ 58%] vmm_system_disk_step4.png
copying images... [ 58%] vmm_system_disk_step4_choose.png
copying images... [ 59%] vmm_customise_tick_step5.png
copying images... [ 59%] vmm_system_disk_sata.png
copying images... [ 59%] vmm_iso_boot.png
copying images... [ 60%] vmm_installation_summary_screen.png
copying images... [ 60%] rockstor_first_login_page.png
copying images... [ 60%] rockstor_update_now_page.png
copying images... [ 61%] rockstor_auto_update_page.png
copying images... [ 61%] rockstor_dashboard_no_drives.png
copying images... [ 61%] vmm_rockstor_listing.png
copying images... [ 61%] vmm_rockstor_details_system_drive_only.png
copying images... [ 62%] vmm_add_data_drive_1.png
copying images... [ 62%] vmm_added_the_data_drives_sata.png
copying images... [ 62%] rockstor_storage_2_data_drives.png
copying images... [ 63%] luks/assign_whole_disk_role.png
copying images... [ 63%] luks/pre_luks_format_tick.png
copying images... [ 63%] luks/post_luks_tick_password.png
copying images... [ 64%] luks/luks_container_icon.png
copying images... [ 64%] luks/luks_boot_up_config_page.png
copying images... [ 64%] luks/luks_auto_unlock_keyfile_create.png
copying images... [ 65%] luks/open_luks_volume.png
copying images... [ 65%] luks/open_luks_volume_info_page.png
copying images... [ 65%] luks/luks_volume_indication_create_pool.png
copying images... [ 66%] luks/luks_volume_indication_pools_page.png
copying images... [ 66%] luks/open_luks_volume_mapped.png
copying images... [ 66%] mdraid-mirror/installation_summary.png
copying images... [ 66%] mdraid-mirror/device_selection.png
copying images... [ 67%] mdraid-mirror/manual_partitioning_1.png
copying images... [ 67%] mdraid-mirror/manual_partitioning_2.png
copying images... [ 67%] mdraid-mirror/manual_partitioning_3.png
copying images... [ 68%] mdraid-mirror/boot_partition_1.png
copying images... [ 68%] mdraid-mirror/boot_partition_2.png
copying images... [ 68%] mdraid-mirror/swap_partition_1.png
copying images... [ 69%] mdraid-mirror/swap_partition_2.png
copying images... [ 69%] mdraid-mirror/root_partition_1.png
copying images... [ 69%] mdraid-mirror/root_partition_2.png
copying images... [ 70%] mdraid-mirror/accept_changes.png
copying images... [ 70%] mdraid-mirror/begin_installation.png
copying images... [ 70%] mdraid-mirror/troubleshooting.png
copying images... [ 71%] mdraid-mirror/rescue.png
copying images... [ 71%] mdraid-mirror/rescue_skip.png
copying images... [ 71%] mdraid-mirror/rescue_btrfs_root.png
copying images... [ 72%] mdraid-mirror/mdraid_second_disk_selection.png
copying images... [ 72%] mdraid-mirror/reuse_md_boot.png
copying images... [ 72%] mdraid-mirror/reuse_md_swap.png
copying images... [ 72%] mdraid-mirror/md_root_subvol.png
copying images... [ 73%] mdraid-mirror/md_home_subvol.png
copying images... [ 73%] mdraid-mirror/md_final_partitions.png
copying images... [ 73%] mdraid-mirror/md_final_summary_of_changes.png
copying images... [ 74%] mdraid-mirror/first_boot_config.png
copying images... [ 74%] mdraid-mirror/first_boot_disks_page.png
copying images... [ 74%] mpsnapshot_all_four.png
copying images... [ 75%] images/initial_appliance_list.png
copying images... [ 75%] images/access_keys.png
copying images... [ 75%] images/add_appliance_form.png
copying images... [ 76%] images/add_appliance_form2.png
copying images... [ 76%] images/appliance_list.png
copying images... [ 76%] images/network_interfaces.png
copying images... [ 77%] images/network_dhcp.png
copying images... [ 77%] images/network_static.png
copying images... [ 77%] nfs_exports_view.png
copying images... [ 77%] delete_nfs_export.png
copying images... [ 78%] images/delete_pool.png
copying images... [ 78%] pre-install-howto/troubleshooting.png
copying images... [ 78%] pre-install-howto/run_memory_test.png
copying images... [ 79%] pre-install-howto/test_this_media.png
copying images... [ 79%] reinstall/reinstall_summary.png
copying images... [ 79%] reinstall/reinstall_destination.png
copying images... [ 80%] reinstall/reinstall_reclaim_space_option.png
copying images... [ 80%] reinstall/reinstall_delete_all.png
copying images... [ 80%] reinstall/reinstall_reclaim_space.png
copying images... [ 81%] reinstall/reinstall_begin_ready.png
copying images... [ 81%] images/splash_screen.png
copying images... [ 81%] images/troubleshooting_screen.png
copying images... [ 82%] images/rescue_screen.png
copying images... [ 82%] images/rescue_shell.png
copying images... [ 82%] images/reset_pw_commands.png
copying images... [ 83%] rufus-howto/rufus34_select_device.png
copying images... [ 83%] rufus-howto/rufus34_rockstor_selected.png
copying images... [ 83%] rufus-howto/rufus34_hash_complete.png
copying images... [ 83%] rufus-howto/rufus34_select_dd.png
copying images... [ 84%] rufus-howto/rufus34_warning.png
copying images... [ 84%] rufus-howto/rufus34_write_in_progress.png
copying images... [ 84%] rufus-howto/rufus34_write_complete.png
copying images... [ 85%] samba_table.png
copying images... [ 85%] services.png
copying images... [ 85%] ntp-config.png
copying images... [ 86%] ad-config.png
copying images... [ 86%] ldap-config.png
copying images... [ 86%] nis-config.png
copying images... [ 87%] sftp/rock_pool.png
copying images... [ 87%] sftp/sftp_share.png
copying images... [ 87%] sftp/sftp_perms.png
copying images... [ 88%] sftp/add_sftp_export.png
copying images... [ 88%] sftp/sftp_export_summary.png
copying images... [ 88%] sftp/gnome_sftp.png
copying images... [ 88%] sftp/gnome_sftp_connected.png
copying images... [ 89%] sftp/cyberduck_sftp.png
copying images... [ 89%] sftp/cyberduck_sftp_connected.png
copying images... [ 89%] sftp/cyberduck_sftp_share.png
copying images... [ 90%] sftp/winscp_login.png
copying images... [ 90%] sftp/winscp_explorer_view.png
copying images... [ 90%] sftp/winscp_commander_view.png
copying images... [ 91%] add_replica.gif
copying images... [ 91%] disable_replica.gif
copying images... [ 91%] images/delete_share.png
copying images... [ 92%] smart/smart_identity_tab.png
copying images... [ 92%] smart/smart_attributes_tab.png
copying images... [ 92%] smart/smart_capabilities.png
copying images... [ 93%] smart/smart_error_logs_tab.png
copying images... [ 93%] smart/smart_self_test_logs_tab.png
copying images... [ 93%] smart/smart_perform_test_tab.png
copying images... [ 94%] smart/no_smart_support.png
copying images... [ 94%] smart/smart_d_logs.png
copying images... [ 94%] smart/add_custom_smart_options.png
copying images... [ 94%] smart/post_custom_smart_options.png
copying images... [ 95%] smart/smart_through_lsi_3ware_raid.jpeg
copying images... [ 95%] images/delete_snapshot.png
copying images... [ 95%] scrub_task.png
copying images... [ 96%] mpsnapshot_daily.png
copying images... [ 96%] tasks_list.png
copying images... [ 96%] task_edit.png
copying images... [ 97%] update-channels/update_channel_options.png
copying images... [ 97%] update-channels/activate_testing_channel.png
copying images... [ 97%] update-channels/activate_stable_channel.png
copying images... [ 98%] update-channels/enable_auto_updates.png
copying images... [ 98%] ups-setup/nut_modes.png
copying images... [ 98%] ups-setup/nut_standalone_eg.png
copying images... [ 99%] ups-setup/nut_netserver.png
copying images... [ 99%] ups-setup/nut_netclient.png
copying images... [ 99%] add-user.gif
copying images... [100%] change-password.gif

copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
program finished with exit code 0
```

Thanks a lot for preparing this to support your rock-on addition, that is excellent in my opinion!

**Comment by MikeMcPherson** [comment]
Thanks very much for your kind words!  You have made contribution very straightforward.  Happy to help.

 

Mike

**Comment by FroggyFlox** [comment]
@MikeMcPherson ,

Following the merge of your rock-on PR, I will now merge your related documentation contribution. As for your rock-on PR, I will try to publish this as soon as possible and it will then be visible on http://rockstor.com/docs/.

Thanks again for writing this documentation alongside your rock-on contribution; that is simply exemplary!

PS: Don't hesitate to let us know if you'd like to add your name/username to the AUTHORS file.

**Comment by MikeMcPherson** [comment]
Thanks, again, to all of you.  You made it straightforward to contribute.  This is my first time contributing to an open source project, and it was much easier than I expected.

 

Thanks for the offer, but I don’t think I belong in the AUTHORS file; what I did is very small and simple compared with the whole project.

 

Mike

**Pull request merged**
