### PR TITLE
Issue#70 email config and test

### LINKED ISSUE #70: email config and test
Add to feature list.
Add walk through and test procedure
I am now working on a pull request for this.

### PR DESCRIPTION
**Pull request by phillxnet**
Adds an email config page and references to this page from multiple places.
A few other little tweaks but nothing major.
fixes #70 
Sphinx v1.2.3 seems happy enough with no unusual warning or errors and Chrome and Firefox render as expected.

### CODE REVIEW

**Comment by phillxnet** [comment]
@schakrava N.B. hold off on merge for a little while as I update images with typo corrections applied in my other merge request on core.  All pretty OK I hope.

**Comment by phillxnet** [comment]
OK sorted now and ready for review.

Please be advised that this last commit may not be admissible as it corrects screen shots as per my proposed and pending pull request on rockstor-core 
https://github.com/rockstor/rockstor-core/pull/797
However all text changes in referenced pull request on core are mostly obvious / safe bets hence me adding the updated images here.
fixes #70 
Thanks.

**Comment by schakrava** [comment]
Thanks @phillxnet, and bonus points for perfectly updating analytics and benchmarks pages with current status.

**Comment by phillxnet** [comment]
@schakrava Thanks and Cheers. We could do with a "Send test email" button really.

**Comment by schakrava** [comment]
Thats a great idea. I'll file the issue if you won't!

**Comment by phillxnet** [comment]
@schakrava if you file I'll update docs / pics on next pass.:)

**Comment by schakrava** [comment]
https://github.com/rockstor/rockstor-core/issues/798

**Pull request merged**
