### PR TITLE
Contrib update

### PR DESCRIPTION
**Pull request by schakrava**

### CODE REVIEW

**Comment by schakrava** [comment]
inappropriate? no way. Your comments helped a lot. I am adding some more changes and I'd welcome more feedback. We should make it super easy for future contributors.

**Comment by phillxnet** [comment]
@schakrava I was thinking we could change the README.md to have a quick explanation of how to build these docs ie the basics of installing sphinx and the "make html" command, that way others wouldn't have to flounder as I did.  Less humps smoother road and all.

I built up a few notes / links as I was working it out myself so I'm game to do this if you like; under another issue I think?

**Comment by schakrava** [comment]
I'll make an effort with styling and grammar. I don't mind if you then polish it in a different pull request.

**Comment by schakrava** [comment]
changing README is also a good idea. please go ahead.

**Pull request merged**
