### PR TITLE
Issue#53 add rock ons intro

### PR DESCRIPTION
**Pull request by phillxnet**
Provides a guide on setting up a Rock-on-root share and links to future rock-on guides are in place with place holders for existing rock-ons that contain a title and "... guide coming soon"

The other guides can then be submitted in additional pull requests.
The added "Rock-ons (Docker Plugins)" page is then referenced where it seemed sensible, ie features, concepts, etc.

This pull request leaves unfixed some Sphinx warnings that I have already addressed in my other pull request, this way they don't clash.

Given these warnings Sphinx v1.2.3 seems happy with it and the resulting html looks dandy.
This way we at least have some documentation on setting up rock-ons.

I think it's ready to merge and publish in time for our new Rockstor release; however I am unavailable until UK tomorrow night (thursday) / friday but can address any issue there after if required.

### CODE REVIEW

**Comment by phillxnet** [comment]
Just popped in a change to recommended minimum rock-ons-root to 5G so as to be consistent with:- https://github.com/rockstor/rockstor-core/pull/711

**Comment by phillxnet** [comment]
I am currently working on this again to incorporate recent changes introduced by https://github.com/rockstor/rockstor-core/pull/711 .

**Comment by phillxnet** [comment]
Will continue tomorrow but got to dash now, if required it is publish spec and I can continue under another pull request; otherwise I'll continue with commits to this pull request.

**Comment by phillxnet** [comment]
I am working on this now.

**Comment by phillxnet** [comment]
This could be merged but if still open tomorrow (UK time) I will try and add the final BTSync rock-on install howto, then we will have the full set.

**Comment by schakrava** [comment]
@phillxnet I am thoroughly impressed by everything in this pull request. You are setting a high bar, thank you!

I've made a few minor corrections and merged the pull request. I figured it's important to publish this without any delay. Hope you don't mind opening another pull request for BTSync and other changes you have planned.

**Comment by phillxnet** [comment]
Thanks, and yes I agree with rapid publish.  I was trying to get it all ready for the release; a bit of mission creep though as was only meant to be the rock-on intro general bit.  I will open another pull request on the BTSync one and round it out there.

**Pull request merged**
