### PR TITLE
Update config backup and restore to document new rock-ons support

### LINKED ISSUE #227: [Config Backup & Restore] Move Rock-on configuration as supported
In preparation for the next rockstor release in which rock-ons will be supported in the config backup & restore feature, we should also update the corresponding section of our documentation:
https://github.com/rockstor/rockstor-doc/blob/master/config_backup/config_backup.rst

Indeed, we currently have the rock-on configuration listed as _planned_, but we should move it to the list of _supported_ configs.

For reference on the feature itself, see the now-merged PR:
https://github.com/rockstor/rockstor-core/pull/2100

We might also take the opportunity to further emphasize that restore a previous backup will **replace** any existing config that is currently supported by the feature (I believe this is the case for all). We already do explain that it will restore the system to a previous state, but we might want to further emphasize that fact with an additional message contained within a "warning block". 

We could also provide further explanation on the restore logic for some features. For services, for instance, all those who were turned ON at the time of backup will be turned back ON after restore. Similarly, for rock-ons, they will all be turned back ON, etc...

@phillxnet , do you think that would be overkill?

### PR DESCRIPTION
**Pull request by FroggyFlox**
Fixes #227 

### This pull request's proposal
Following the recent support for rock-ons in the Config Backup & Restore feature, this pull request proposes to first update the documentation to reflect that new support, but also further develop notes to the users, and specifies a few implied (but missing) points.

#### Details
1. _Rock-ons_ are moved from the list of planned features to the list of supported features.
2. We now specify that _exports_ are included with regards to AFP/NFS/Samba configuration.
3. Add warning block clearly specifying that the current system settings will be partially overwritten by a restore.
4. Add a _special notes_ section with further details on the expected behavior.

#### Sphinx build
```
>make html
Running Sphinx v2.3.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 61 source files that are out of date
updating environment: [new config] 61 added, 0 changed, 0 removed
reading sources... [100%] windows-shadow-copy
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] windows-shadow-copy
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] change-password.gif     
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build\html.

Build finished. The HTML pages are in _build/html.
```

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [x] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Comment by FroggyFlox** [comment]
@phillxnet, I believe this is ready for review, but let me know if you'd prefer to see more details in some section.

**Comment by phillxnet** [comment]
@FroggyFlox This is great and much appreciated. Nice to have our docs kept in line with the code. And thanks again for adding these extra capabilities to the code in the first place :).

Merging and publishing shortly.

**Comment by phillxnet** [comment]
@FroggyFlox Sorry to be taking so long on this one. It's now published and looks good.

Well done and I really like the additional section there. As you say more explicit. We have a typo on the "restore a" bit but it's nothing and best we get it published rather than delay, plus I don't expect this will be the last time we update the docs :).

**Comment by FroggyFlox** [comment]
Hi @phillxnet,

On the contrary, thanks a lot for being so quick!

My apologies on the typo.. A simple "patch" PR should be enough to correct that isn't it?

**Comment by phillxnet** [comment]
> My apologies on the typo.. A simple "patch" PR should be enough to correct that isn't it?

Possibly, or we just tack it on to one of our next pr's. Mixing and matching pr's in the docs isn't  as problematic as in the core as it's only us humans that have to deal with it. :)

**Comment by FroggyFlox** [comment]
Thanks... I think I'll simply make a patch-PR, then, as I'm sure I'll forget about it otherwise.

Thanks again!

**Pull request merged**
