### PR TITLE
Change Bitwarden to Vaultwarden

### PR DESCRIPTION
**Pull request by RlndVt**
Don't misrepresent Vaultwarden/Bitwarden and use the proper project name.

> To ease and accelerate the PR submission, please use the template below to provide all required information.
> Please see our "Contributing to Rockstor documentation" in our [Rockstor's documentation](http://rockstor.com/docs/contribute_documentation.html)

Fixes #NA

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [x] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Comment by phillxnet** [comment]
@RlndVt Nice catch and thanks for the submission. Much appreciated.

However here in the docs we are referencing our Rock-on name also so we could do with similar matching changes in our: https://github.com/rockstor/rockon-registry repository.

I.e. take a look at the following Rock-on definition:

https://hub.docker.com/r/bitwardenrs/server

As it seems we are still using the deprecated image also:
https://hub.docker.com/r/bitwardenrs/server

> ⚠️ This image is deprecated ⚠️
> Bitwarden_RS has been renamed to Vaultwarden, the new image is located here:
> 
> vaultwarden/server

and it's associated root.json referemce:

https://github.com/rockstor/rockon-registry/blob/master/root.json#L3

So it would be great if we could have co-referenced issues/pull requests in both repositories to address your findings.

Again thanks for the submission here and do let us know if you are game to pop in a similar matching pr in the rock-ons definition repository as then we can coordinate the name change across docs and Rock-ons Web-UI entries which would be ideal. No worries otherwise but this way the attribution is more direct which is nice. No authors file in that repo, such as we use here for the CC-BY-SA in the docs, but we use the git/GitHub contributors tally and periodically announce contributors on the forum such as here: https://forum.rockstor.com/t/rock-ons-changelog/6469/33

Also be sure to create issues for each pull request as it helps us keep track of changes with further attribution.

Cheers and again thanks for update/fix here.

**Comment by RlndVt** [comment]
Thanks @phillxnet. 

I've created issues in both repositories with matching PR: https://github.com/rockstor/rockon-registry/pull/297.

**Review by phillxnet — APPROVED** [review]
@RlndVt Thanks for stepping up to this one. Much appreciated. And thanks again for addressing the related Rock-on re-name. Nice.

**Comment by phillxnet** [comment]
@RlndVt Once we have the Rock-on repo name change pull request reviewed we can pop these in as a set.

**Comment by phillxnet** [comment]
@RlndVt Apologies for the delay on this one. But I think we can pop this one and your matching rock-on repo pull request in very soon.

**Comment by FroggyFlox** [comment]
@RlndVt , @phillxnet ,

Now that https://github.com/rockstor/rockon-registry/pull/297 is merged and published, I'm going to merge and publish this one too.

Thanks again for all this!

**Comment by FroggyFlox** [comment]
This is now published at https://rockstor.com/docs/interface/overview.html#rock-ons-without-write-ups

**Pull request merged**
