### PR TITLE
update transmission rock-on doc. Fixes #124

### LINKED ISSUE #124: update transmission rock-on doc
Due to a partner issue in the rockstor-registry a usability change to the suggested share should be reflected in the docs.
In the process the images could be updated to reflect the new theme. Take care to have images and text match.

partner issue in rockstor-registry repo:-
https://github.com/rockstor/rockon-registry/issues/3

I am currently undertaking these changes and preparing a pull request.

### PR DESCRIPTION
**Pull request by phillxnet**
As per a recently submitted pr in rockstor-registry this patch set updates the transmission rock-on doc accordingly, including images.

make html with Sphinx v1.2.3 produced no errors and the output is as expected in Chrome and Firefox.

Fixes #124

### CODE REVIEW

**Comment by phillxnet** [comment]
Note that this pr relates to a partner rockstor-registry pr:-
https://github.com/rockstor/rockon-registry/pull/4

**Comment by phillxnet** [comment]
@schakrava Ready for review.

**Comment by schakrava** [comment]
Excellent my friend! thanks!

**Comment by phillxnet** [comment]
@schakrava Cheers.

**Pull request merged**
