### PR TITLE
best practice before install. Fixes #118

### LINKED ISSUE #79: add media check directions
In the install section we should include or point to a howto on confirming the created media's integrity.
ie via "Test this media and install Rockstor" boot option.

### LINKED ISSUE #118: best practice before install doc
Might be a nice thing to have so we can point at it for initial - pre install issues such as iso corruption or flaky USB or disks with weird partition tables and the like.
Could go in as a howto maybe.

### PR DESCRIPTION
**Pull request by phillxnet**
Adds a Pre-install Best Practice (PBP) guide in howto section and links to it from our Quick Start guide and our Install section.
Compiles with Sphinx v1.2.3 with no errors and displays as expected in Chrome and Firefox.
Fixes #118 
Fixes #79

### CODE REVIEW

**Comment by phillxnet** [comment]
Pull request ready for review.

**Comment by phillxnet** [comment]
@schakrava  Sorry last minute change just popped in there.

**Comment by schakrava** [comment]
Thanks @phillxnet. very detailed!

**Comment by phillxnet** [comment]
@schakrava Cheers.

**Pull request merged**
