### PR TITLE
Missing links in basic concepts section #183

### PR DESCRIPTION
**Pull request by Dbzs**
Added _Concepts tag to the document, and added :ref: links for all the sections except Smart Manager, and Secure Shell.  Checked rendering in online Sphinx editor, was not able to test in a browser install.

### CODE REVIEW

**Comment by phillxnet** [comment]
I am currently reviewing this pull request.
Linking to issue #183 for context.

**Comment by phillxnet** [comment]
```
make html     
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.5
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 61 source files that are out of date
updating environment: 61 added, 0 changed, 0 removed
reading sources... [100%] windows-shadow-copy                                                                                                                        
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] windows-shadow-copy                                                                                                                         
generating indices... genindex
writing additional pages... search
copying images... [100%] change-password.gif                                                                                                                         
copying static files... WARNING: html_static_path entry '/home/philip/projects/rockstor-doc/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

Build finished. The HTML pages are in _build/html.
```
No additional errors or warnings:
Check rendering via local python webserver:
```
pushd ./_build/html; python -m SimpleHTTPServer; popd
~/projects/rockstor-doc/_build/html ~/projects/rockstor-doc
Serving HTTP on 0.0.0.0 port 8000 ...
```
using the following browser url:
```
http://localhost:8000/
```

**Comment by Dbzs** [comment]
@phillxnet thanks for the review.  I've just installed Python and Sphinx, just working out how to point Sphinx at my local Rockstor directory.

**Comment by phillxnet** [comment]
@Dbzs This looks just fine. Checked rendering via the temporary python webserver trick and all additional links look and work as intended.

Two minor point that will help going forward:

- I like for all link targets to be lowercase, don't think it matters but that way we don't have to think about it.
- When you do a pull request, if you pop in a "Fixes #number-of-issue" on it's own line then when it gets merged it auto closes that issue. Just a nice to have and also provides a link to the relevant issue. See https://help.github.com/articles/closing-issues-using-keywords/ for details.

Merging as all looks to be good and Sphinx 'make html' was happy.

**Comment by Dbzs** [comment]
Thanks for the tips, I should have been able to work out the no caps from all the other labels I linked to.

**Pull request merged**
