### PR TITLE
Rearrange and add new content

### PR DESCRIPTION
**Pull request by vinima**
Add backup on time machine, building personal cloud, why only btrfs

### CODE REVIEW

**Comment by schakrava** [comment]
Welcome to the fun of contribution @vinima!

**Comment by phillxnet** [comment]
@vinima Hello; this looks much better.

Nothing to do with your changes, which are great, but in pulling down your branch and looking over the faq I noticed the "contact us" link is broken, I think it should be "http://rockstor.com/about-us.html#contact" . I'm afraid I missed this last time I was in this file and given you have this pull request open already with changes on this file (faq.rst) it seemed appropriate to comment and might help keep the merge request labour down.
Hope this helps.

If you like I can do a merge request on your branch with this change; but that might be overkill, also I'm on UK time so got to dash now for a bit.

Apologies if this is inappropriate.

**Comment by vinima** [comment]
@philip, thanks for bringing this change/issue to my attention.  I did not
notice it.  I won't be able to make a fix until Monday (PST). So, if you
can get to it before, please feel free to merge this change on my branch.
If you are busy with something else, I will take care of it. Thanks again
for noticing.

**Comment by phillxnet** [comment]
@vinima it seems like github is not happy with the approach I was to take; oh well.  At least we know about it and if you are OK sorting then great, otherwise we will just have to pop it in another pull request.

**Comment by vinima** [comment]
@philip, I will make the change and merge it today - thanks for looking
into it.

**Comment by vinima** [comment]
@phillxnet I've fixed 'Contact Us' link.

**Pull request merged**
