### PR TITLE
update plex rock on guide and rock ons list. Fixes #135

### LINKED ISSUE #135: update plex rock-on guide and rock-ons list
Update the docs to reflect a recent update to our Plex Rock-on to add both a plexpass personality and a transcoding share option. There are now also additional port options available.

Update 'available rock-ons' list while in the area.

### PR DESCRIPTION
**Pull request by phillxnet**
Updates the plex Rock-on section to reflect the currently included image.
Also updates almost all plex related images and add a few to assist with configuring newer sections such as the UID, GID, and VERSION form to allow for plexpass use or just latest image stipulation.

"make html" using Sphinx v1.2.3 compiles without any additional errors.
Also updated available Rock-ons in overview section.

Displays as expected in both Chrome and Firefox.

There is more work to be done on polishing the Plex guide but this pr improves what was there significantly and is now representative of our new linuxserver.io based rock-on.

N.B. GitLab CE (a very recent Rock-on addition) is included in this pr in the recently added "Rock-ons without write-ups" section.

### CODE REVIEW

**Comment by phillxnet** [comment]
@schakrava sorry forgot the last push hold on.

**Comment by phillxnet** [comment]
@schakrava Sorry just forgot to add that last push to the pr.

All done now and ready for review.

Fixes #135

**Comment by phillxnet** [comment]
@schakrava Sorry it seems there may be a problem with the recently updated plex rock-on with regard to finding itself. Seems to only affect some installs and looks like it affected me on this install.
So we could push this as is or wait until the plex problem is rooted out and I can quickly update this pr with the findings.
Linking to the forum thread detailing the issue:-
https://forum.rockstor.com/t/plexpass-and-problems/1310/4

**Comment by phillxnet** [comment]
Adding additional informative forum thread actively dealing with the same plex image issue:
https://forum.rockstor.com/t/plex-media-server/1321

**Comment by phillxnet** [comment]
Needs minor modification and retest to reflect the recent changes in the Plex rockon in the following commit:
https://github.com/rockstor/rockon-registry/commit/dca3235dd672e63af2b0f45157fe44b61a3e0b9e
- [ ] ports section reduced back to 1 entry.
- [ ] removal of transcode share.
- [ ] last section modified to show new behaviour of fresh install ie should now find itself ok.

**Comment by schakrava** [comment]
Thank you @phillxnet ! Let me know when you want me to review and merge.

**Comment by phillxnet** [comment]
@schakrava  OK I think this is a significant improvement on what we have.
Still not as good as it could be but a step in the right direction.
It can always be improved in another pr so that we can get this one out for now.
It is at least consistent now with our new Rock-on.

**Comment by schakrava** [comment]
Thank you @phillxnet. Really nice work with a lot of detail in the face of still changing behaviour. Shows you care :)

**Comment by phillxnet** [comment]
@schakrava Thanks.

**Pull request merged**
