### PR TITLE
Add usage of docker-sphinx

### LINKED ISSUE #272: Add documentation for using Sphinx Docker container to make html
Hello, I propose to add in the documentation how to build HTML using Sphinx docker container: https://github.com/sphinx-doc/docker

### PR DESCRIPTION
**Pull request by 20design**
Fixes #272 

### This pull request's proposal

- Add documentation about usage of docker-sphinx
- Add `code-block` type

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [x] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### Sphinx output
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v3.5.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.

### CODE REVIEW

**Comment by phillxnet** [comment]
@20design That was quick. Well done.
I've only glanced at it but did notice some tab chars in there. I think we had best stick to only spaces, as per our code. Not really sure how we are doing on that front within the docs but just thought I'm mention it as spaces are universal and tabs are not. Which in turn helps with keeping diffs more readable. I don't think we've covered this before so just mentioning it on this pr incidentally. @FroggyFlox we should probably add this advise to the docs on docs contributing :) .

**Comment by 20design** [comment]
@phillxnet I converted the indentation to spaces. 
The file contained spaces and tabs before :-)

**Comment by phillxnet** [comment]
@20design Re:

> @phillxnet I converted the indentation to spaces.
> The file contained spaces and tabs before :-)

That's great. Yes, I'm afraid we have yet to get our act together re the tabs/spaces thing in the docs. Should now be done on the python side however. Thanks for sorting that out in this file and apologies for bring this up. I just wanted to mention it as I've failed to before. We most likely have them mixed through the docs unfortunately.

This pr is a great addition by the way. And maybe we can re-visit to simplify if we do get around to having our own pre-configured docker image for this. Or if we manage to further reduce our Sphinx addon on dependencies. At least we have now dropped the problematic YouTube one now. That one ended up loading our doc users browsers with cookies that I'm trying to avoid.

**Review by FroggyFlox — APPROVED** [review]

**Comment by FroggyFlox** [comment]
@20design ,

Again, please accept my apologies for not tending to your pull request earlier. I just got the time to look at it now and it looks great!
I'm going to merge it now and publish it as soon as I can.

Thanks again!

**Pull request merged**
