### PR TITLE
add discourse to docs. Fixes #114

### LINKED ISSUE #114: add discourse to rock-ons section
Extend the Available Rock-ons section to include a Discourse installation guide.

### LINKED ISSUE #115: Fix formatting of md howto re howtos list
It seems there is something in "Mirroring Rockstor OS using Linux Raid" that is upsetting the Howtos listing as subsections are appearing as additional howto's.

### PR DESCRIPTION
**Pull request by phillxnet**
No errors when processing with Sphinx v1.2.3
Results tested in Chrome and Firefox.

Reduced initial scope of issue by removing jenkinsci, will create a separate issue for this.
Fixes #114 
N.B. also Fixes #115 to reduce web update overhead.

Pull request ready for review.

### CODE REVIEW

**Comment by phillxnet** [comment]
@schakrava I have now almost completed the Jenkins rock-ons section and will add it to this pull request within the next couple of hours (hopefully sooner) so it may be worth holding off until that is done. Thanks and no worries otherwise.

**Comment by phillxnet** [comment]
@schakrava sorry messed up the #'s there a bit. last three commits actually belong to #117, never mind.

**Comment by phillxnet** [comment]
Again ready for review.
Now Fixes #117 as well.

**Comment by schakrava** [comment]
Thanks @phillxnet! Nice, useful and great timing. really appreciate it!

**Comment by phillxnet** [comment]
@schakrava Thanks and Cheers.

**Pull request merged**
