### PR TITLE
add min device size to min sys requirements. Fixes #150

### LINKED ISSUE #150: add min device size to min sys requirements
Thanks to @rocklobster in the following forum thread for this suggestion.
Rockstor currently ignores any drive that is < 1GB in size so we should indicate this minimum in the "Quick Start" guide under "Minimum system requirements".
As this value is still very small for modern volumes I think the docs should stress a minimum recommended of 4GB per device as some balance operations for example can fail to complete as expected with very small disks or when there is very little space available.
~~A link to the btrfs FAQ might also be useful on this entry.~~

### PR DESCRIPTION
**Pull request by phillxnet**
Basic update to our 'Minimum system requirements' section, within 'Quick start' section.

- added dual core spec to min CPU.
- added <1GB dev ignored.
- added >5GB dev recommended.
- added 4GB+ RAM recommended.
- normalised on 'drive'.
- added if sys usb key then only fast variants.
- added ssd recommended for sys dev.
- added UPS as recommended.
- stressed 'data use only' for additional non system drives.
- minor rewording.

Ready for review

Fixes #150 

Tested via Python 3 variant of Sphinx v1.6.5, no additional errors or warnings. Resulting html displays as intended in latest Chrome and Firefox and existing links in changed section continue to work.

### CODE REVIEW

**Comment by phillxnet** [comment]
To aid review I am attaching an html rendering (Chrome) of the resulting changes as per specified Sphinx:

post-pr-min-sys-requirements

The intention here is to only update the bullet points and address the referenced issue.

**Comment by phillxnet** [comment]
@FroggyFlox Could you give a second opinion on these changes as I'd like to commit this pr on my current docs run.
Thanks.
We can always update later to include auto root snapshot enablement via larger system disk once we get to actually dishing out the next gen stuff.

**Comment by FroggyFlox** [comment]
That looks good to me, @phillxnet.

I cannot test the Sphinx build myself but changes look ok to me--as far as I know. I'm not an expert as to requirements but from my own experience and what I've seen from users in the forum, I do appreciate the bump for USB recommendations (if used for OS).

Just a minor comment regarding the UPS bullet point. Indeed, it may seems like one HAS to have a NUT-compatible UPS in order to run Rockstor. Maybe it was the intent, but I feel like "(compatible with NUT is preferred)" would be an alternative wording.
I'm a little nitpicking here so it's up to you as you're the most familiar with this aspect of Rockstor anyway ;-)

Thanks for all the work on this report!

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for the review and double check on the Sphinx. Much appreciated.

On the NUT compatibility point it's actually a requirement (if a UPS is used) as we rely on NUT to do the automated shutdown. It has a fairly large hardware coverage but it's capabilities / compatibility varies quite a lot from model to model. However it's pretty much our only option.

I'll merge this shortly then and thanks again for the review.

**Pull request merged**
