### PR TITLE
Add section on Rock-on post-install customization. Fixes #189

### LINKED ISSUE #189: Add section on Rock-on "Add Storage" feature
The Rock-on summary settings as well as the "Add Storage" to an already installed Rock-on feature are not currently described in the documentation.
Adding explanation and an example use of the latter would be beneficial as it is a critical and very convenient (and thus popular?) feature of the Rock-on system.

### PR DESCRIPTION
**Pull request by FroggyFlox**
Fixes #189 

The current PR add two subsections in the current "Rock-on overview" section describing the Rock-on summary settings as well as use case for two post-install customization features:
- Add Storage
- Add Label

Please note that **the latter section is dependent on the following pending PR** in the rockstor-core repo: https://github.com/rockstor/rockstor-core/pull/1999

### CODE REVIEW

**Comment by FroggyFlox** [comment]
Thanks for verifying this, @phillxnet, I'll correct the errors you pointed out. 

I'll need to re-setup my Sphinx environment as I have been lazy and only used a VScode extension with live-preview for verifying the content.

I'll commit as soon as possible.

**Comment by FroggyFlox** [comment]
Thanks again @phillxnet for verifying this PR.
I've made the requested changes in the two most recent commits (ee39b6c and 0febe65).

The `make html` now runs without error on my end:
```
$ python -V
Python 3.6.5

$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.8.1
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 61 source files that are out of date
updating environment: 61 added, 0 changed, 0 removed
reading sources... [100%] windows-shadow-copy
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] windows-shadow-copy
generating indices... genindex
writing additional pages... search
copying images... [100%] change-password.gif                                   essage.png
copying static files... WARNING: html_static_path entry 'C:\\[path_to]\\_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

The HTML pages are in _build\html.

Build finished. The HTML pages are in _build/html.
```

**Comment by phillxnet** [comment]
@FroggyFlox I finally got around to merging this pr. Very nice. And much appreciated.

As per your testing Sphinx was happy and remains so here just now.

I know we have a lead here on actual available features, ie your awaiting merge rockstor-core merge labels issue, already referenced, but it don't think that matters too much as it's only a matter of time. Plus we at least get the commonly applicable 'add storage' doc additions which will be nice.

I'm also keen to get this in before we have any conflicting pull requests, which will only make more work for all concerned.

Thanks for your efforts on this.

**Comment by FroggyFlox** [comment]
Thanks a lot, @phillxnet, for the merge and for spotting my mistakes before that!

**Pull request merged**
