### PR TITLE
dhcp and static network configuration guide including pngs

### PR DESCRIPTION
**Pull request by phillxnet**
Basic guide on how to observer and re-configure Rockstor's network settings.  Includes minimal guidance on using dhcp and static arrangements.  Includes pics to demonstrate both configurations and stresses the need to manual adjust browsers URL when changing the ip.

Formatting checked in both Firefox and Chrome and Sphinx v1.2.3 processed to html without error.

### CODE REVIEW

**Comment by phillxnet** [comment]
fixes #9

**Comment by schakrava** [comment]
Thanks @phillxnet , this is great!

I am able to see the changes on the web, but for some reason when I manually pull the branch, github doesn't think there are any changes to pull. Not sure what the problem is, but I am ok merging this from github website. One question though, in the Static IP section of network.rst, you write "in your DNS server's dynamic pool range" which I don't understand. Did you mean DHCP server or am I missing something here? Everything else makes sense.

**Comment by phillxnet** [comment]
Opps sorry yes that should have been DHCP server; do you want me to change it here? Wanted to get it sorted ready for OSCON.

**Comment by schakrava** [comment]
yes, please change and push since I am unable to pull your changes. I'll just merge by button for this one :)

**Comment by phillxnet** [comment]
OK I sorted it. Thanks.

**Comment by phillxnet** [comment]
Well you don't hang around do you :)

**Comment by schakrava** [comment]
Thank you sir! I am squeezing in some work before heading over to pick up pass etc.. Need to make it count when I can :)

**Pull request merged**
