### PR TITLE
Update "detached disk" section re exclamation mark #291

### LINKED ISSUE #291: Update "detached disk" section re exclamation mark
Thanks to forum member papaskitch for highlighting this omission. The current disk section is out of date with regard to modern disk removal procedure (exclamation mark) for devices currently associated with a pool. It is proposed that we update this section to include the new step required for removing currently pool associated detached disks via the "!" icon which then frees them from their pool association so that they can be deleted via the already documented bin icon that appears there after.

Associated forum thread: https://forum.rockstor.com/t/failed-to-delete-the-share-tm-error-from-the-os-failed-to-mount-pool-seagate-due-to-an-unknown-reason-command-used-usr-bin-mount-dev-disk-by-label-seagate-mnt2-seagate/7921/6

### PR DESCRIPTION
**Pull request by phillxnet**
Adds subsections of Pool Associated, and Non Pool Associated along with all updated images. The linked Pool Resize/ReRaid section is also updated and improved along with new Web-UI screen captures as well.

An example is given of restoring a degraded raid 1 pool on minimum disk members (2) where one is detached. The user is taken through the less preferred path of changing the raid level via the wizard and then re-running the wizard to then remove the detached disk's pool association. This serves to address micro installations where only 2 drives can be attached at any one time. And covers 2 of the 3 wizard options that required more attention: reraid and remove. Disk add is often a trivial event that requires little explanation and almost always adds space. Although a note is added to indicate that an accompanying
raid level change can in fact reduce available space.

Fixes #291
Ready for review.

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [x] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Comment by phillxnet** [comment]
@FroggyFlox No worries if you have no time to glance at this. It looks to render OK and is likely more informative / up-to-date than what we have. Let me know either way and I'll take it from there.

I have a related doc issue pending (#236) that is dependant upon this pull requests conclusion.

**Comment by FroggyFlox** [comment]
> @FroggyFlox No worries if you have no time to glance at this. It looks to render OK and is likely more informative / up-to-date than what we have. Let me know either way and I'll take it from there.
> 
> I have a related doc issue pending (#236) that is dependant upon this pull requests conclusion.

Sorry for not having looked at it, @phillxnet. I indeed am unable to test its build at the moment and won't for a little while, unfortunately, so don't hesitate to go ahead without a review from me... my apologies.

**Comment by phillxnet** [comment]
@FroggyFlox No worries. I'll merge and get this out. I double check the rendering and I think we are OK.
The disk / pool text can always be improved so it's an ongoing effort anyway.

**Comment by phillxnet** [comment]
PR products in production.

**Pull request merged**
