### PR TITLE
Replace Manpage links (Issue #453)

### LINKED ISSUE #453: Replace manpage links with opensuse manpage server entries
Currently, three manpage links are creating errors during the automated linkcheck activity on github. Since we are running on OpenSUSE, @FroggyFlox suggested to use the OpenSUSE manpage server as a replacement (which also does not have any advertisements with its pages).

This seems to affect two documents:

[interface/storage/file_sharing/nfs_ops.rst](https://github.com/Hooverdan96/rockstor-doc/blob/926786dd45ba58ca68e5eebb13510099763c084b/interface/storage/file_sharing/nfs_ops.rst) - L47, L50, L157

[interface/system/services.rst](https://github.com/Hooverdan96/rockstor-doc/blob/926786dd45ba58ca68e5eebb13510099763c084b/interface/system/services.rst) - L145

One thing to consider though is the OpenSUSE manpages are showing output of TW based functionality ... which I think only might have some implications for the sssd-ad link that would be replaced (based on the forum conversations and version differences between TW and LEAP in that regard). The other 2 links refer to nfs (exports and nfs client)
https://manpages.opensuse.org/Tumbleweed/sssd-ad/sssd-ad.5.en.html
https://manpages.opensuse.org/Tumbleweed/nfs-kernel-server/exports.5.en.html
https://manpages.opensuse.org/Tumbleweed/nfs-client/nfs.5.en.html

### PR DESCRIPTION
**Pull request by Hooverdan96**
Fixes #453.

### This pull request's proposal
Changes to be committed:
	modified:   interface/storage/file_sharing/nfs_ops.rst
	modified:   interface/system/services.rst
- replace manpage links with opensuse sourced ones
- some cosmetic cleanup

### Checklist
- [X] With the proposed changes no Sphinx errors or warnings are generated.
- [X] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Comment by Hooverdan96** [comment]
The linkcheck error occurring here is unrelated to the above pull request. The failure of the pocketmine link is actually addressed in Pull request #452.

**Review by phillxnet — APPROVED** [review]
@Hooverdan96 Thanks for getting these links updated. Much appreciated.

Thanks also for sorting out a variety of other typos here. And it's surprising the number of older Rock-on references we have re it's prior beta status.

**Comment by phillxnet** [comment]
@Hooverdan96 Nice to see the link check passing locally again. Cheers.

**Comment by phillxnet** [comment]
PR product PRODUCTION published.

**Pull request merged**
