### PR TITLE
Update "Developers" section re recent build changes #319

### LINKED ISSUE #319: Update "Developers" section re recent build changes
Due to a change/update in authentication mechanism re pypi we have had to alter our build procedure a little. Mainly due to our use of a now outdated python 2 based build system. See: https://github.com/rockstor/rockstor-core/issues/1877

Previously we setup and executed our source build by:
```
bootstrap.py -c buildout.cfg
buildout -N -c buildout.cfg
```

This was affected by staggered brown outages intended to inform those using older build systems such as ours that changes were afoot. These changes have now become permanent and represent a deprecation of non-SNI compatible clients. 

Update our doc entries to reflect the work around we are now using:

```
zypper --non-interactive install python2-pip
pip2 install zc.buildout
buildout bootstrap
```
Thanks to @FroggyFlox for researching the origin of these difficulties and presenting the above work around. Much appreciated.

Apologies for the delay in establishing this issue.

## Components:
- [x] Move to suggesting the use of a v4 install instance. Contributors should be familiar with this install and it has many of the rpm's dependencies and little else so is a good start.
- [x] add install command for required developer dependencies- Build VM  section in contribute page.
- [x] Fix above detailed build command chanages.
- [x] Be opinionated about the build directory, there's no harm and it's a quicker read.
- [x] Remove dead YouTube link in this section.
- [x] Remove some overly chatty bits in Local git repo setup section.
- [x] Remove adding name to authors file as we have now only 2 in there but 35 git contributors. It is suspected that this is due to the first 2 including an email. This also represents an overhead for those doing small patches.
- [x] Update /opt/rockstor-dev/var/log "ls -la" entry as we now have no ztask.log but a new entry or two for huey.
- [x] Add systemd services info.
- [x] Add updating info/context re rpm.
- [x] Move contribute.rst to [Semantic Liefeeds](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).

### PR DESCRIPTION
**Pull request by phillxnet**
Due to a change/update in authentication mechanism re pypi we have had to alter our build procedure a little. Reflect these changes in our developer contributor section.

Fixes #319 
@FroggyFlox This ended up being far more extensive that I had originally thought.
Creating this pull reqeust to aid in further development / discussion if need be.
I have, potentially controversially, move to semantic line feeds. I'm rather hoping I can win you over on this one. Given my recent work on https://github.com/rockstor/rockstor-website/pull/22 I have found it to be far easier to work with when editing/writing and it should help with future edits and translations.
N.B. I have yet to do proper sphinx/formatting validation but will push any required changes that turn up.

## Includes improvements re:
- Brevity.
- Readability.
- Consistency.
- Ordering.
- Update to V4 "Built on openSUSE" base os.
- Preference for using a rockstor-installer derived instance.
- Removed dead and distracting YouTube links.
- Removed redundant and completely neglected AUTHORS link to rockstor-core.
- Better segregation and interdependency explanation of build steps.
- Improve on-boarding ease/speed via tips to enable cut-paste setups.
- Add info on associated systemd services.
- Add info on updating re rpm and source installs.
- Move contribute.rst to semantic line feeds.

## Testing.
The above changes were proofed vai the use of all included tips and suggestion so that an existing fresh UEFI install derived from our current latest pre-build installer (4.0.9-0 profile Leap15.3.x86_64) was transitioned into a development source install. Build from our current master branch.

### CODE REVIEW

**Comment by phillxnet** [comment]
OK so it looks like my convinience link to the testvm Web-UI is breaking our link checker:
```
(contribute/contribute: line  280) broken    https://buildvm/ - HTTPSConnectionPool(host='buildvm', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4bf198aaf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
I'll look to pushing a fix.

**Comment by FroggyFlox** [comment]
@phillxnet , thanks a lot for all of this, that looks a lot more extensive than I would have thought! Thanks a lot for revamping this section; it'll definitely help users setting up their environment.

I unfortunately don't think I'll have time to have a proper look at it and test it in the very short term, so feel free to merge it if you'd like!

**Comment by phillxnet** [comment]
@FroggyFlox Cheers and no worries. Just having a final look over final formatting now and if no glaring issues I'll go ahead and merge. I think it's an overall plus. Plus we have to revisit a little later to add a testing section (own issue soon) and to inform folks about the soon to be established testing branch. So any anomalies can be addressed at that time also.

**Comment by phillxnet** [comment]
Pull request changes are now in production.

**Pull request merged**
