### PR TITLE
remove beta status of UPS/NUT etc support #295

### LINKED ISSUE #295: remove beta status of UPS/NUT etc support
In our dedicated UPS section docs/ups-setup/ups_setup.html we still have the following in bold:

> Please note that this feature is in beta testing and not yet recommended for production use.

Given we have now had this capability for some time and it has undergone a couple of minor bug fixes with no recent reports of issues, it is proposed that we now remove this beta status. Numerous forum reports have been submitted that have not gone on to indicate any issues and of late we have 'heard nothing'. This bodes well for removing the 'beta' label now.

### PR DESCRIPTION
**Pull request by phillxnet**
Fixes #295 
@FroggyFlox Ready for review.

## Includes:
- Update of Features table.
- Standardised on Web-UI (no GUI) in features table.
- Added Dashboard, Networking (IPv4/IPv6), Rocknets, Reboot/Shutdown/Suspend scheduled tasks, Rock-ons auto reinstalled, Sell-in-a-box, SSL cert entry, Log Manager, User/Group management.
- Removed WebDAV (planned) & RESTful API.

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [x] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Comment by phillxnet** [comment]
@FroggyFlox Curiously we have a difference in the rendering of this table if served up via a localhost Python web server:
```
make html
pushd ./_build/html; python3 -m http.server 8000; popd
```
python-http-server

Or a full blown web server (via our buildbot test server):

Real-http-server

**Comment by FroggyFlox** [comment]
> @FroggyFlox Curiously we have a difference in the rendering of this table if served up via a localhost Python web server:

Interesting... and good to know and keep in mind when testing how it renders. I did notice a difference when testing the fix for #285: the local `python http.server` did not throw the mix HTTP/HTTP content blockage message and the external call was going through.

I'll get to your PR as soon as I can; thanks for taking care of this one!

**Review by FroggyFlox — APPROVED** [review]
@phillxnet,

Sorry it took me so long... it all looks good to me on my end and it was a much needed update to this table!
I do notice an inconsistency in the alignment of the columns headers vs the rows below, but that's something we should address in a separate PR, maybe after taking care of #288.

Thanks a lot!

**Comment by FroggyFlox** [comment]
This is now published ;-)
Thanks again!

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for the review and taking care of the merge and publish. Much appreciated.

Yes, I noticed the miss alignment.  We are using what I thought was a standard table so I didn't look any further.
Agreed that fixing: "Styles for admonitions are not defined" #288
is far more of a priority. Maybe there is some Sphinx setting to control table alignment or the like. Or some css setting it depends upon.

Thanks again for the leg work on the test and publish..

**Pull request merged**
