### PR TITLE
Note testing branch as preferred for core contributions #357

### LINKED ISSUE #357: From 4.1.0-0 stable release, the new testing branch is default for contributions.
Our current developer on-boarding docs mention only the master branch. As from our recent 4.1.0-0 stable git tag rpm release we are now to develop our testing channel rpms from a newly established testing branch within git. The master branch is now reserved for our stable releases and so our docs should reflect this new split.

The new split to branch based development is to enable the massive code wide changes that are required for our pending Language and tools wide upgrade. E.g.:
https://github.com/rockstor/rockstor-core/issues/1877
and it's indicated, in-development, sub-part dependency of:
https://github.com/rockstor/rockstor-core/issues/2254

This 'movement' within the project should also be made clear on the developers page so that folks can choose where they think their contributions are to be submitted. But in almost all cases all code submissions will now go to our testing branch first. Cherry picking may then take place but the projects main focus is now to lift our dependencies across the board and move testing towards the next stable but via newer Python and django and associated libraries. The following issue in an example of this efforts beginning by moving what was one of our oldest dependencies ztaskd to be replaced by one one of our newest:

https://github.com/rockstor/rockstor-core/pull/2283

However such 'up-lift' is nigh on impossible until we approach first our Django up-lift and then our Python up-lift. Which in turn will allow for a further Django upgrade and we can then approach the remaining dependencies piecemeal; including our now in need of some attention build system.

The above details should at least be indicated to new contributors to provide context. But in short all new contributions hit testing first and only long time contributors should be contributing directly to master give it's essentially a stop-gap to maintain a usable build as we undertake much needed maintenance work.

It should also be noted that testing is again soon to be non-functional as there is soon to be the contribution of ongoing Django updates that are extensive and will have breaking changes that are to be addressed in an ongoing manner in the new testing channel.

### PR DESCRIPTION
**Pull request by phillxnet**
As from git tag 4.1.0-0 we have begun extensive dependency update work in a new testing branch. Make this clear in developer docs and alter guidelines/instructions accordingly.

Fixes #357

## Additionally includes
- minor typo fixes
- fix for malformed/mis-configured forum link

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [x] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Comment by phillxnet** [comment]
@FroggyFlox If you have time, could you give these changes a quick glance over, just in case. I've kept the changes minimal here which I think is the way to go. From experience we mostly have already had contact with folks embarking on this endeavour so we really only need a concise guide here; hence avoiding a lot of background info with these additions.

In time we will need additional sections to address new build systems we hope to bring in but that is for another issue/pull-request set as and when.

**Comment by FroggyFlox** [comment]
That looks good to me, and a good addition!
I only have time for a quick look at it for the moment but it's indeed an important addition.

Thanks a lot for taking care of it!

**Comment by phillxnet** [comment]
@FroggyFlox Cheers and agreed. I'll merge and publish.

**Comment by phillxnet** [comment]
Patch product production published.

**Pull request merged**
