### PR TITLE
Fix image sizes (#258)

### LINKED ISSUE #258: Images aspect ratios are not respected
Throughout the documentation, most images are displayed with an aspect ratio that does not fit the image's original. As a result, these images appear compressed along their width. This appears contradictory at first to the use of the `:scale:` option of the `.. image::` directive, which should scale down both height and width of the image.

After a quick inspection of the final html code, we can see that while the width and height of the image appear to be properly scaled down, we are hitting the *page* width limit for most of these, which thus results in such a compressed display. For instance:
image
In the example above using a `:scale: 80%` option, we can see that:
- the html code does scale down properly: `style="width: 931.2px; height: 602.4px;`
- but the image width hits the page limit: `width: 730px; height: 602.4px;`

Let's thus look at the `.. image::` directive documentation:
https://docutils.sourceforge.io/docs/ref/rst/directives.html#image

> width : length or percentage of the current line width
>     The width of the image. Used to reserve space or scale the image horizontally. As with "height" above, when the "scale" option is also specified, they are combined.
>
> scale : integer percentage (the "%" symbol is optional)
>     The uniform scaling factor of the image. The default is "100 %", i.e. no scaling.

As a result, it appears more appropriate to use the `:width:` option without defining the height to have a proper scaling. Testing this with the same image as in the example above:
**current**:
```
.. image:: rockons_root_share.png
   :scale: 80%
   :align: center
```

**alternative**:
```
.. image:: rockons_root_share.png
   :width: 100%
   :align: center
```
image

We can see that the image now uses the full width of the page (as instructed by `:width: 100%`), resulting in an image with the same aspect ratio as the original, which looks a lot better.

Of course, this would need to be verified for all images, so implementing this (if accepted) might be better done progressively on a PR-by-PR basis.

### PR DESCRIPTION
**Pull request by FroggyFlox**
Fixes #258 
@phillxnet , I'm submitting this PR as draft at first again, so that I can check its rendering in Apache.

### This pull request's proposal
Some images were included with an inappropriate `:width: 100%` setting.
This commit fixes that by either:
- removing the width setting for images smaller than page width
- setting a width setting less than 100% for a few images for which
  it was appropriate

 This commit also includes some minor ReST reformatting (respect max
 line length of 79 char).

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [x] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Comment by FroggyFlox** [comment]
All seems to look at intended in our Apache2 webserver so I'll switch this PR as ready for review.

**Review by phillxnet — APPROVED** [review]
@FroggyFlox This is a nice docs wide re-asses of our image treatment. Well done.

I was particularly surprised by:
before-after-left-align

Much better for our smaller pics.

Thanks for taking the time to see to this. Again much appreciated.

**Comment by phillxnet** [comment]
@FroggyFlox Apologies for taking so long in getting to this and your other recent doc pull requests.

All good from what I can tell. I'll get to publish these two very shortly and note here.

**Comment by phillxnet** [comment]
@FroggyFlox 
This pr and it's predecessor are now published.

Again thanks for your efforts. Docs looking better all the time.

**Pull request merged**
