### PR TITLE
Update statement on IPv6 support. #361

### LINKED ISSUE #361: Correct "IPv6 currently disabled at boot" in Features
Prior to our first v4 "Built on openSUSE" stable release, we removed the system wide IPv6 disabled (via kernel boot option) status.
This disablement was only in effect during development; i.e. during a phase within our last testing channel run. It is still the case that we offer no Web-UI component for IPv6 but we do not disable it system wide any-longer.

We need to correct this statement in our Features table that features in our front docs page:
https://rockstor.com/docs/

### PR DESCRIPTION
**Pull request by FroggyFlox**
Fixes #361 
@phillxnet, ready for review.

### This pull request's proposal
This PR includes two small changes:
- Clearly indicate that while IPv6 configuration via webUI is not possible, IPv6 configuration is possible at the command line.
- Update CSS to have `<table>` take 100% width to ease clarity.

@phillxnet, note that I have not yet been able to verify the rendering using an Apache server.

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [x] I have added my name to the AUTHORS file, if required (descending alphabetical order).

### CODE REVIEW

**Review by phillxnet — COMMENTED** [review]
@FroggyFlox My apologies for taking my time to get to this one. All looks good except for the width bit:

## Before
before

## After
after

I don't see any extra width. Looking into this a little now.

**Comment by phillxnet** [comment]
@FroggyFlox So far this is as far as I've gotten regarding the table formatting inheritance:

feature-table-formatting-dev-mode

**Comment by FroggyFlox** [comment]
> I don't see any extra width.

:(
In my test, the increase in the overall table width was slight but enough to display a clear separation between the "Planned" and the notes.

I'll try to look into this further when I get the chance.

**Comment by phillxnet** [comment]
@FroggyFlox I say we pop this in as-is actually; given it has obvious benefits. Plus with some playing around here I see that our trailing space is 'factored in': i.e. if we:

```
   +--------------------------------------------------+----------+------------------------------------------------------------+
   | Sharing via :ref:`NFS<nfs>`                      | prod     | Network File-System cross platform enterprise file access  |
   +--------------------------------------------------+----------+------------------------------------------------------------+
```

and use the in rst width override of:

```
.. table::
   :widths: 45 10 55
```
And indent our table we end up having rst control of column width plus we get this:

table-format-option

Which looks to be full width.

So I've opened the following issue to address using the new width by reformatting our rst table content.
It's pretty fussy thought, hence the new issue.
"Improve features table format" #390

**Comment by FroggyFlox** [comment]
Thanks for bringing up the `:widths:` option... I didn't know about it!

> and use the in rst width override of:
> 
> ```
> .. table::
>    :widths: 45 10 55
> ```

If I'm correct, these should equal to 100%, isn't it? How about we do `45 10 45`? This gives me the following:
image

**Comment by phillxnet** [comment]
@FroggyFlox PR product published.

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for seeing to this. I can't believe we had that Dsk typo on this front page also !!
Oh well, bit by bit. And nice we now have the IPv6 status updated in docs at last.
Cheers.

**Pull request merged**
