### PR TITLE
Update Config Backup page to include scheduled tasks as supported

### LINKED ISSUE #215: [Config Backup-Restore] Update "Scheduled Tasks" as included in backups
Since a recent PR, scheduled tasks are supported in the config Backup & Restore feature.
Currently, the related section details them as being _planned_ but not supported yet.

We should now list them as **supported** and provide some additional details such as the fact that all types of scheduled tasks are supported, for instance.

I can take care of this small edit if this sounds like a good plan.

### PR DESCRIPTION
**Pull request by FroggyFlox**
Fixes #215.

This PR simply moves **Scheduled Tasks** from the list of settings planned to be implemented to the list of currently supported ones.

I also updated all screenshots in this page with some using the latest Stable release (3.9.2-50).

@phillxnet, ready for review.

## Sphinx output
```
> make html
Running Sphinx v2.2.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] config_backup/config_backup
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] config_backup\conf_uploaded.png
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build\html.

Build finished. The HTML pages are in _build/html.

```

### CODE REVIEW

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for this. Nice to keep our docs updated.

I propose that we only publish this once 3.9.2-51 has been published? As that should include the relevant pr of yours that contained this config save/restore extension:

https://github.com/rockstor/rockstor-core/pull/2059

**Comment by FroggyFlox** [comment]
> I propose that we only publish this once 3.9.2-51 has been published? As that should include the relevant pr of yours that contained this config save/restore extension:

Of course! For some reason, I forgot about that little "detail"... sorry.

**Comment by phillxnet** [comment]
@FroggyFlox Apologies, I seem to have dropped the ball on this doc pr of yours.
We have had 3.9.2-51 out now since 16th December.

Are we still good to publish this 'as is' ?

If I don't hear back I'll assume so, asking just in case.

**Comment by FroggyFlox** [comment]
No worries, @phillxnet... I personally completely forgot about it :-( 

I believe it is still ready to merge, so feel free to publish any time you want.

Thanks!

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for this pull request, most appreciated.
And most timely, or would have been had I have been 'on it'.

Looks to now be published as expected, although one of my chrome instances refuses to refresh it's local cache for the new pics!!

**Pull request merged**
